### ISSUE TITLE
Fealty Agenda deck check error

### ISSUE THREAD

**Issue by DoubleAitch** [TassLehoff/AGoTv2-OCTGN#10]
The current deck check for the Fealty Agenda gives a warning when there are exactly 15 Neutral cards in the deck but this is a legal amount.  The warning should only appear when there are 16 or more.

**GameDatabase/30c200c9-6c98-49a4-a293-106c06295c05/scripts/actions.py**
line 440:  `if NeutralCount<15:`
should be:  `if NeutralCount<16:`

**Comment by TassLehoff** [comment]
Thanks
