### ISSUE TITLE
TassLehoff look this

### ISSUE THREAD

**Issue by fatelesscn** [TassLehoff/AGoTv2-OCTGN#22]
Hi TassLehoff, I'm a friend of Snowfrost. He is quite busy recently and could hardly work on octgh, while I'm doing the job instead of him. Now I'm working on the automatic resolving process of the game, and would feel really grateful if you could lend some help. I put my version on Github and you can have a look, if possible.

by fateless

**Comment by TassLehoff** [comment]
Contact me by email, just ask my email to snowfrost ;)

**Comment by fatelesscn** [comment]
i try to email you ,do you read? 

my project is finish 4.2.https://github.com/fatelesscn/Agot2.0cn

i wanto build some function to your offical version

**Comment by TassLehoff** [comment]
No email received.
Your project look very good, try to merge it with official version ;)

**Comment by fatelesscn** [comment]
i am working alone for this big project ,so it finish very slowly.do you have a team? want to do it together?

**Comment by TassLehoff** [comment]
I don't have a team and i'm not a coder, so i can't help you, sorry. But i'm realy happy by your work :)

**Comment by fatelesscn** [comment]
well...at first i can merge some simple functions for this.

i can creat a changelogfile to show you how can the functions work.

i think the language is not problem. let us to work it perfect!

**Comment by TassLehoff** [comment]
Like you want, you're the boss ;)

**Comment by fatelesscn** [comment]
i have a question,how can you update the code to the offical version of octgn

**Comment by TassLehoff** [comment]
I build a nupkg with O8buildgui.exe and i upload the nupkg on myget.org if this that you want to know.
But please we need to find a way to comunicate otherwise, so email, irc, skype like you want ;)

**Comment by fatelesscn** [comment]
chinese network is very hard to that . so find me in skype:octgnfateless
