### ISSUE TITLE
Incorrectly labelled as unique

### ISSUE THREAD

**Issue by Blobquest** [TassLehoff/AGoTv2-OCTGN#31]
GameDatabase/30c200c9-6c98-49a4-a293-106c06295c05/sets/7f08ef9f-dd47-415b-b002-827a0defcd2a/set.xml
Line 750
`<property name="Unique"                     value="Yes"/>`

Should be 
`<property name="Unique"                     value="No"/>`

**Comment by fatelesscn** [comment]
yes，confirm
@TassLehoff
