### ISSUE TITLE
Attachments discarded with DEL go back to hand

### ISSUE THREAD

**Issue by mplain** [TassLehoff/AGoTv2-OCTGN#42]
instead of the discard pile.

**Comment by fatelesscn** [comment]
it's correctly ,maybe you discarded the card with keywords 'Terminal'

**Comment by mplain** [comment]
In manual mode I press DEL to discard Ice from play (to use it) or Milk (because of Confiscation), and the card goes to my hand instead of the discard pile. Is this intended?

**Comment by fatelesscn** [comment]
Ice's ability is to discard pile,but the del order is disc card,so if you want to use ice's ability,just move it manually.
the milk, i check it correctly.

**Comment by mplain** [comment]
DEL is to discard a card from play, right? Not to use an ability on that card. I just expected DEL to discard cards from play regardless of what abilities they have...

**Comment by fatelesscn** [comment]
wait for new version,when i make the card'ability,it wil be ok
