### ISSUE TITLE
Bear and the Maiden Fair stacks own deck incorrectly

### ISSUE THREAD

**Issue by ocbarron** [TassLehoff/AGoTv2-OCTGN#45]
There seems to be a bug when you play Bear and the Maiden Fair **on yourself**--all cards you look at get moved to the bottom of the deck. The cards you choose to be on the top of the deck will get moved to the bottom, in that order. For example, if I try to stack my deck as follows: Renly, Randyll, Margaery on top, in that order, then put Roseroad and Garden Caretaker on bottom, all five cards will go to the bottom, and Renly will be my bottom card, followed by Randyll, Margaery, then Roseroad and Garden Caretaker. 

Again, BAMF appears to work fine when it's used to stack other people's decks, but it fails consistently and predictably when you use it on your own deck.

![bamf2](https://cloud.githubusercontent.com/assets/22734274/19224697/51695aa2-8e59-11e6-8788-bd15d65b8d4d.png)
![bamf3](https://cloud.githubusercontent.com/assets/22734274/19224699/5e273476-8e59-11e6-9cc4-583009dbd01b.png)

**Comment by fatelesscn** [comment]
it will be fixed
