### ISSUE TITLE
Ghosts of Harrenhal Chapter pack set.xml errors

### ISSUE THREAD

**Issue by Bullgator351** [TassLehoff/AGoTv2-OCTGN#51]
There are some errors in the card titles in the Ghosts of Harrenhal chapter pack.
In multiple places the apostrophe is replaced by the string "null".
Two cards omit the word "The" from their title.

**Comment by Bullgator351** [comment]
I opened a pull request with corrections.  You might want to harmonize the version numbers before the build.

**Comment by fatelesscn** [comment]
thx
